name: Keep Fork Active

on:
  schedule:
    - cron: '0 0 */50 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Keep alive
        run: |
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "GitHub Action Keepalive"
          git commit --allow-empty -m "🔄 Keep fork active - $(date +'%Y-%m-%d')"
          git push
